"""
This type stub file was generated by pyright.
"""

from delta.exceptions.base import ConcurrentAppendException, ConcurrentDeleteDeleteException, ConcurrentDeleteReadException, ConcurrentTransactionException, ConcurrentWriteException, DeltaConcurrentModificationException, MetadataChangedException, ProtocolChangedException

__all__ = ["DeltaConcurrentModificationException", "ConcurrentWriteException", "MetadataChangedException", "ProtocolChangedException", "ConcurrentAppendException", "ConcurrentDeleteReadException", "ConcurrentDeleteDeleteException", "ConcurrentTransactionException"]
