"""
This type stub file was generated by pyright.
"""

from pyspark.errors.exceptions.base import PySparkException

class DeltaConcurrentModificationException(PySparkException):
    """
    The basic class for all Delta commit conflict exceptions.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


class ConcurrentWriteException(PySparkException):
    """
    Thrown when a concurrent transaction has written data after the current transaction read the
    table.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


class MetadataChangedException(PySparkException):
    """
    Thrown when the metadata of the Delta table has changed between the time of read
    and the time of commit.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


class ProtocolChangedException(PySparkException):
    """
    Thrown when the protocol version has changed between the time of read
    and the time of commit.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


class ConcurrentAppendException(PySparkException):
    """
    Thrown when files are added that would have been read by the current transaction.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


class ConcurrentDeleteReadException(PySparkException):
    """
    Thrown when the current transaction reads data that was deleted by a concurrent transaction.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


class ConcurrentDeleteDeleteException(PySparkException):
    """
    Thrown when the current transaction deletes data that was deleted by a concurrent transaction.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


class ConcurrentTransactionException(PySparkException):
    """
    Thrown when concurrent transaction both attempt to update the same idempotent transaction.

    .. versionadded:: 1.0

    .. note:: Evolving
    """
    ...


