repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^notebooks/
      # Run the formatter.
      - id: ruff-format
        exclude: ^notebooks/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        types: [json, yaml]
        additional_dependencies:
          - prettier@2.1.2
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.9
    hooks:
      - id: uv-lock
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v5.0.0
  #   hooks:
  #     - id: pretty-format-json
  #       args: [--autofix, --no-sort-keys]
