repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.14
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
        exclude: "**/*.ipynb"
      # Run the formatter.
      - id: ruff-format
        exclude: "**/*.ipynb"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        types: [json, yaml]
        additional_dependencies:
          - prettier@2.1.2
