"""
This type stub file was generated by pyright.
"""

import fastsql
import polars as pl
from pydantic import BaseModel

def convert_to_polars(model: BaseModel): # -> DataFrame:
    ...

def convert_polars_to_arrow(df: pl.DataFrame):
    ...

def get_table_info(table_name: str) -> tuple[str, str, str]:
    ...

def get_uri(catalog: str, schema: str) -> str:
    ...

def get_fastsql_db(table_name: str) -> fastsql.Database:
    ...

def get_serving_endpoints(): # -> Iterator[ServingEndpoint]:
    ...

def get_spark(): # -> SparkSession:
    ...

