"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping

"Parse numpy-style docstrings"
__all__ = ['Parameter', 'NumpyDocString', 'dedent_lines']
Parameter = ...
def strip_blank_lines(l):
    "Remove leading and trailing blank lines from a list of lines"
    ...

class Reader:
    """A line-based string reader."""
    def __init__(self, data) -> None:
        ...
    
    def __getitem__(self, n):
        ...
    
    def reset(self): # -> None:
        ...
    
    def read(self): # -> Literal['']:
        ...
    
    def seek_next_non_empty_line(self): # -> None:
        ...
    
    def eof(self): # -> bool:
        ...
    
    def read_to_condition(self, condition_func): # -> list[Any]:
        ...
    
    def read_to_next_empty_line(self): # -> list[Any]:
        ...
    
    def read_to_next_unindented_line(self): # -> list[Any]:
        ...
    
    def peek(self, n=...): # -> Literal['']:
        ...
    
    def is_empty(self): # -> bool:
        ...
    


class ParseError(Exception):
    def __str__(self) -> str:
        ...
    


SECTIONS = ...
class NumpyDocString(Mapping):
    "Parses a numpydoc string to an abstract representation"
    sections = ...
    def __init__(self, docstring, config=...) -> None:
        ...
    
    def __iter__(self): # -> Iterator[str]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __getitem__(self, key): # -> list[Any]:
        ...
    
    def __setitem__(self, key, val): # -> None:
        ...
    


def dedent_lines(lines, split=...): # -> list[str] | str:
    """Deindent a list of lines maximally"""
    ...

