"""
This type stub file was generated by pyright.
"""

from typing import Any

def evalgen_wizard_model(model: str, temperature: float = ..., max_tokens: int = ..., top_p: float = ...): # -> ChatDatabricks:
    ...

def evalgen_criteria_processing(criterias: list[dict], prompt_template: str, vars_context: dict[str, Any] | None = ..., bad_example: list[str] | None = ...): # -> list[Any]:
    ...

def evalgen_criteria_generation(prompt: str, user_feedback_prompt: str, output_file: str): # -> None:
    ...

