"""
This type stub file was generated by pyright.
"""

from delta.tables import DeltaTable
from delta.pip_utils import configure_spark_with_delta_pip

__all__ = ['DeltaTable', 'configure_spark_with_delta_pip']
