"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional, Union
from pyspark.sql.column import Column

ExpressionOrColumn = Union[str, Column]
OptionalExpressionOrColumn = Optional[ExpressionOrColumn]
ColumnMapping = Dict[str, ExpressionOrColumn]
OptionalColumnMapping = Optional[ColumnMapping]
