"""
This type stub file was generated by pyright.
"""

def configure_spark_with_delta_pip(spark_session_builder, extra_packages=...):
    """
    This is the DBR edge implementation of this function which is a NOOP.
    """
    ...

