name: pr
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  pre-merge-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4


      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.16"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-extras --locked

      - name: Run checks
        run: make check

